// FoxPro expressions evaluated on every row of the edge table, in real FoxPro and,
// after conversion, in SQL Server. Each one must give the same value on every row.

/** Expressions that return text. They are wrapped in PADR() so FoxPro does not size the column from the first row. */
export const TEXT_EXPRESSIONS = [
  'ALLTRIM(c)', 'LTRIM(c)', 'RTRIM(c)', 'TRIM(c)', 'UPPER(c)', 'LOWER(c)', 'UPPER(m)', 'LOWER(v)',
  'LEFT(c, 3)', 'LEFT(c, 0)', 'LEFT(c, 20)', 'RIGHT(c, 3)', 'RIGHT(ALLTRIM(c), 2)', 'RIGHT(c, 20)', 'LEFT(m, 10)',
  'SUBSTR(c, 2)', 'SUBSTR(c, 2, 3)', 'SUBSTR(c, 20)', 'SUBSTR(c, 3, 0)', 'SUBSTR(c, 12)', 'SUBSTR(m, 6, 3)',
  "c + '|'", "ALLTRIM(c) + '|' + ALLTRIM(cn)", "cn + '|'", "v + '|'", "ALLTRIM(v) + '|'", "c + cn + v",
  "NVL(cn, 'null')", "NVL(cn, '') + '|'", "NVL(v, c)", "NVL(ALLTRIM(cn), '-')",
  "PADL(ALLTRIM(c), 8, '*')", 'PADL(ALLTRIM(c), 3)', "PADR(ALLTRIM(c), 5, '-')", "PADL(i, 6, '0')", 'PADL(n, 10)',
  "PADL(ALLTRIM(c), 10, 'ab')", "PADR(ALLTRIM(c), 10, 'ab')", "PADL(c, 14, '.')",
  "STRTRAN(c, 'a', 'X')", "STRTRAN(c, 'ab')", "STRTRAN(m, 'abc', '-')", "STRTRAN(c, ' ', '_')", "STRTRAN(c, 'B', 'b')",
  'CHR(65 + MOD(id, 26))', "REPLICATE('ab', 3)", "SPACE(3) + 'x'", "REPLICATE(LEFT(c, 1), 3)",
  'STR(n)', 'STR(n, 10, 2)', 'STR(n, 12, 3)', 'STR(n, 5)', 'STR(n, 4, 1)', 'STR(i)', 'STR(y, 12, 2)', 'STR(nn, 6)',
  'STR(n, 3)', 'STR(i, 3)', 'STR(n * 1.005, 12, 2)', 'STR(i / 3, 8, 3)', 'STR(-n, 10, 1)',
  'TRANSFORM(i)', 'TRANSFORM(d)', 'TRANSFORM(l)', 'TRANSFORM(c)', 'TRANSFORM(dn)',
  'DTOC(d)', 'DTOS(d)', 'DTOC(dn)', 'DTOS(dn)', 'DTOC(d, 1)', 'DTOS(GOMONTH(d, 1))',
  "IIF(l, 'yes', 'no')", "IIF(n > 0, 'pos', IIF(n < 0, 'neg', 'zero'))", "IIF(ISNULL(cn), 'null', cn)",
  "ICASE(i < 0, 'neg', i = 0, 'zero', i < 10, 'small', 'big')", "ICASE(ISNULL(nn), 'n/a', nn > 10, 'many', 'few')",
  "IIF(EMPTY(c), '(blank)', ALLTRIM(c))", "EVL(ALLTRIM(c), '(blank)')", "EVL(cn, 'n/a')", "UPPER(LEFT(ALLTRIM(c), 1)) + LOWER(SUBSTR(ALLTRIM(c), 2))",
  "PADL(ALLTRIM(STR(i)), 5, '0') + '-' + DTOS(d)", "STRTRAN(STR(n, 12, 2), ' ', '0')", "ALLTRIM(STR(YEAR(d))) + '/' + PADL(MONTH(d), 2, '0')", "LEFT(c, AT(' ', c + ' ') - 1)",
  "IIF(l AND n > 0, 'A', IIF(!l AND n > 0, 'B', IIF(l, 'C', 'D')))", "SUBSTR(DTOS(d), 5, 2) + '-' + RIGHT(DTOS(d), 2)", "IIF(c = 'ab', 'match', 'no')", "IIF('b' $ c, 'has b', 'none')",
];

/** Expressions that return a number or a date. */
export const VALUE_EXPRESSIONS = [
  'LEN(c)', 'LEN(ALLTRIM(c))', 'LEN(cn)', 'LEN(v)', 'LEN(m)', 'LEN(c + cn)', 'LEN(TRIM(c))', 'LEN(LTRIM(c))',
  "AT('a', c)", "AT('A', c)", "ATC('B', c)", "AT('b', m)", "AT('abc', m)", "AT(' ', c)", "ATC('ABC', m)", "AT('ß', c)",
  'ASC(c)', 'ASC(SUBSTR(c, 2, 1))', 'VAL(c)', 'VAL(cn)', 'VAL(v)', "VAL('12.5')", 'VAL(STR(n, 12, 2))',
  'n * 2', 'n / 3', 'i / 2', 'i / 3', '(i + 1) / 2', 'n + nn', 'nn * 2', 'i * n', 'y * 2', 'y / 3', 'n - i', '-n', 'i - inn',
  'i / 4 * 4', '1 / 3', '10 / 4', 'n * i / 7',
  'MOD(i, 3)', 'MOD(i, -3)', 'MOD(n, 2)', 'MOD(inn, 5)', 'MOD(id, 4)', 'i % 3', 'id % 5',
  'INT(n)', 'INT(n / 2)', 'INT(-n)', 'ROUND(n, 1)', 'ROUND(n, 0)', 'ROUND(n, -1)', 'ROUND(y, 2)', 'ROUND(n * 1.005, 2)',
  'ROUND(i / 3, 2)', 'ROUND(n / 7, 3)', 'ROUND(-n, 1)',
  'ABS(n)', 'ABS(i)', 'SIGN(n)', 'SQRT(ABS(n))', 'CEILING(n)', 'FLOOR(n)',
  'i ^ 2', 'n ** 2', '2 ^ id', 'y + $1.5', 'id ^ -1', 'i * 2 % 5', '(i + 7) % 4',
  "OCCURS('a', c)", "OCCURS('ab', m)", "OCCURS('', c)", "RAT('a', m)", "RAT('b', c)", "RAT('zz', c)", 'EVL(nn, -1)', 'EVL(i, 99)', 'DTOT(d)', 'DTOT(d) + 90',
  'LEN(ALLTRIM(c) + ALLTRIM(cn))', 'ROUND(VAL(c) / 3, 2)', 'INT(MOD(n, 7)) + LEN(cn)', 'YEAR(GOMONTH(d, id)) * 100 + MONTH(GOMONTH(d, id))',
  'NVL(nn, 0)', 'NVL(inn, -1)', 'NVL(nn, n)', 'IIF(l, 1, 0)', 'IIF(ISNULL(nn), 0, nn) + 1',
  'YEAR(d)', 'MONTH(d)', 'DAY(d)', 'DOW(d)', 'YEAR(dn)', 'MONTH(dn)', 'QUARTER(d)', 'DAY(GOMONTH(d, 1))',
  'd + 1', 'd - 1', 'd + 30', 'd - id', 'd + i', 'd - dn', 'dn - d', 'd - {^2000-01-01}', '{^2030-01-01} - d',
  'GOMONTH(d, 1)', 'GOMONTH(d, -1)', 'GOMONTH(d, 12)', 'GOMONTH(d, -12)', 'GOMONTH(dn, 1)', 'GOMONTH(d, id)',
  't + 60', 't - 3600', 't - {^2000-01-01 00:00:00}', 'TTOD(t)', 'HOUR(t)', 'MINUTE(t)', 'SEC(t)', 'YEAR(t)', 'd - TTOD(t)',
  'CTOD(DTOC(d))', 'DATE(2026, 1, id)', 'DATE(YEAR(d), MONTH(d), 1)', 'GOMONTH(DATE(YEAR(d), MONTH(d), 1), 1) - 1',
];

/** Conditions, tested both as WHERE x and as WHERE NOT (x) so three-valued logic is covered. */
export const CONDITIONS = [
  "c = 'ab'", "c = 'abc'", "c == 'abc'", "c = ''", "c # 'ab'", "c <> 'ABC'", "c != ''", "ALLTRIM(c) = 'a'", "c == ''",
  'c = cn', "cn = 'x'", "cn # 'x'", "cn == ''", "cn = ''", "v = 'ab'", "v == 'ab'", "c = 'abcdefghijklmnop'",
  "c > 'abc'", "c >= 'ab'", "c < 'B'", "c <= 'abc'", "c > ''",
  "'b' $ c", "'B' $ c", "'' $ c", 'cn $ c', "'fox' $ m", "'x' $ cn", "ALLTRIM(cn) $ c",
  "c LIKE 'a%'", "c LIKE '%c'", "c LIKE '_bc'", "c LIKE 'abc'", "c LIKE '100%'", "c LIKE 'A%'", "cn LIKE 'a%'", "c LIKE '%'",
  "c LIKE '%b%'", "v LIKE 'ab'", "c NOT LIKE 'a%'",
  "INLIST(c, 'ab', '12')", 'INLIST(i, 0, 7, 100)', "c IN ('abc', 'ABC')", "c NOT IN ('ab')", 'i IN (1, 2, 7)', 'i NOT IN (0, 7)',
  "INLIST(cn, 'x', 'ab')", 'inn IN (3, 7)', 'inn NOT IN (3, 7)',
  'BETWEEN(i, 0, 7)', 'BETWEEN(n, -1, 1)', "BETWEEN(c, 'a', 'b')", 'i BETWEEN 0 AND 7', 'BETWEEN(d, {^2026-01-01}, {^2026-12-31})',
  'BETWEEN(inn, 0, 7)', 'n NOT BETWEEN 0 AND 10',
  'EMPTY(c)', 'EMPTY(cn)', 'EMPTY(v)', 'EMPTY(n)', 'EMPTY(nn)', 'EMPTY(i)', 'EMPTY(inn)', 'EMPTY(y)', 'EMPTY(l)', 'EMPTY(m)',
  'EMPTY(d)', 'EMPTY(dn)', 'EMPTY(t)', 'EMPTY(ALLTRIM(c))', "EMPTY(NVL(cn, ''))", 'EMPTY(n * 0)', 'EMPTY(LEFT(c, 2))',
  'ISNULL(cn)', 'ISNULL(nn)', 'ISNULL(dn)', '!ISNULL(t)', 'ISNULL(cn) OR EMPTY(cn)', 'ISNULL(c)',
  'l', '!l', 'NOT l', 'l AND n > 0', 'l OR ISNULL(cn)', 'l = .T.', 'l = .F.', 'l # .T.', '(l OR n > 0) AND !(i = 0)', 'l AND !EMPTY(cn)',
  'n > 0', 'n >= 0 AND n < 2', 'nn > 0', 'nn = 0', 'inn <> 0', 'n = nn', 'y > n', 'i = inn', 'n # nn', 'nn > 0 OR nn <= 0',
  'd > {^2026-01-01}', 'd = {^2026-01-31}', 'd >= dn', 'dn < d', 'd - dn > 0', 'YEAR(d) = 2026', 'MONTH(d) = 2 AND DAY(d) > 28',
  't > {^2026-01-01 00:00:00}', 'TTOD(t) = d', 'd # dn', 'dn = {^2026-01-01}',
  'MOD(id, 2) = 0', 'i / 2 = 3.5', 'INT(n) = n', 'LEN(ALLTRIM(c)) > 3', "AT('a', c) > 0", "UPPER(c) = 'ABC'", "LOWER(c) == 'abc'",
  "LEFT(c, 2) == 'ab'", 'cn IS NULL', 'cn IS NOT NULL', "!EMPTY(cn) AND cn # 'x'", "NOT (c = 'abc' OR c = 'ABC')", 'NVL(nn, 0) = 0',
  "m = 'memo'", "m == ''", "c + cn = 'abc         x'", "ALLTRIM(c) == ALLTRIM(cn)", "c = ALLTRIM(cn)", "ALLTRIM(cn) = 'a'",
  ".T.", ".F.", "1 = 1", "id > 3 AND .T.", 'y > $1', 'y = $12', 'i % 2 = 1', 'i ^ 2 > 50',
  "ALLTRIM(c) # 'a'", "ALLTRIM(c) > 'ab'", "ALLTRIM(c) <= 'ab'", "m # 'memo'", "v > 'ab'", "cn <= 'a'", "cn > 'a'", "c >= ''", "c < ''",
  "'ab' = c", "'abc' = cn", "'x' # cn", "'abcdefghijklmnopq' = c", "'' = c", "'ab' = ALLTRIM(c)", "'ab' == c", "'abc' == c",
  "c = 'ab' OR cn = 'x'", "c = 'ab' AND !l", "NOT c = 'ab'", "!(cn = 'x') AND !ISNULL(cn)", "UPPER(ALLTRIM(c)) = 'AB'", "LEFT(c, 2) = 'ab'",
  "c LIKE 'a%c'", "c LIKE '%'", "c LIKE ''", "c LIKE '_'", "cn LIKE '%b'", "m LIKE '%fox'", "c LIKE '%!%'", "cn LIKE 'a_b'", "v LIKE '[x]'",
  "OCCURS('a', c) > 0", 'EVL(nn, 5) = 5', 'd = TTOD(t)', 'DTOT(d) = t', 'd + 1 > dn', 'd - 1 < dn', 'GOMONTH(d, 1) > dn', 'EMPTY(d - dn)', 'EMPTY(i * n)', 'EMPTY(c + cn)', 'EMPTY(STR(i))', 'EMPTY(LEN(ALLTRIM(c)))',
  'i IN (0)', "cn IN ('x')", "cn NOT IN ('x', 'ab')", "INLIST(ALLTRIM(c), 'abc', 'ABC')", 'INLIST(d, {^2026-01-31}, {^2026-01-01})', 'BETWEEN(dn, d - 400, d + 400)', 'BETWEEN(t, {^2026-01-01 00:00:00}, {^2026-12-31 23:59:59})',
];
